@echo off
mkdir build
echo Compiling mug test build...
g++ -std=c++11 -DTEST_BUILD -o build\mug.exe src\*.cpp

echo Running unit tests...
build\mug.exe

echo Compiling mug...
g++ -std=c++11 -o build\mug.exe src\*.cpp

echo Compiling code_gen_tests...
build\mug.exe -c -o build\code_gen_tests.o tests\code_gen_tests.mug

echo Linking...
gcc tests\code_gen_tests.c build\code_gen_tests.o -o build\code_gen_tests.exe

echo Running code_gen_tests...
build\code_gen_tests.exe
